[package]
name = "bls2brs"
version = "1.0.0"
authors = ["ns <ns@brickadia.com>", "kmschr <kmschr@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1"
regex = "1"
bl_save = "0.2"
brs = "0.1"
wexit = "0.1"
